source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftString_Example', :exclusive => true do
  pod 'SwiftString', :path => '../'
end

target 'SwiftString_Tests', :exclusive => true do
  pod 'SwiftString', :path => '../'
  pod 'SwiftHamcrest'
end
